---
local_db: jdbc:h2:/var/vcap/services/maxdb/maxdb_node.db
base_dir: /var/vcap/services/maxdb/
ip_route: 127.0.0.1
mbus: nats://localhost:4222
index: 0
logging:
  level: debug
pid: /var/vcap/sys/run/maxdb_node.pid
available_storage: 1024
node_id: maxdb_node_1
max_db_size: 20
max_log_size: 20
max_user_conns: 20
migration_nfs: /mnt/migration
maxdb:
  sysdbauser: test
  sysdbapassword: test123
  dbmuser: DBADMIN
  dbmpassword: test123
  osuser: sdb
  ospassword: sdbPass
  host: localhost
  port: 7210
  

# z_interval: 30
# max_nats_payload: 1048576
